### ISSUE TITLE
VSCode environment configurator fails fresh install oneAPI basekit.

### ISSUE THREAD

**Issue by AdamMiltonBarker** [intel/vscode-oneapi-environment-configurator#5] opened 2021-07-11 07:13 UTC
Posted in forum also https://community.intel.com/t5/Intel-oneAPI-Base-Toolkit/VSCode-environment-configurator-fails/m-p/1297614#M1625 

Not a question just letting you know the environment configurator for VSCode does not work. Fresh install of basekit on Windows 10, command prompt works fine, when trying to start the environment in vscode it pops up with Error 1, then after that window is closed it pops up as if it has worked but it hasn't.

![oneapi-bug](https://user-images.githubusercontent.com/6291410/125186021-3d4da500-e228-11eb-8951-45eec3bb9342.JPG)
![oneapi-bug-2](https://user-images.githubusercontent.com/6291410/125186022-3e7ed200-e228-11eb-81e2-dd156d5e45a3.JPG)
![oneapi-bug-3](https://user-images.githubusercontent.com/6291410/125186024-3f176880-e228-11eb-9780-fc27761d886e.JPG)

**Comment by sbobko** [comment] 2021-07-13 19:54
@AdamMiltonBarker Hi,
Could you run setvars in PS directly, without our extension? something in the form of .\setvars.bat
![image](https://user-images.githubusercontent.com/46919374/125516149-ff0aa076-e989-480c-9b82-a4a6fd452da5.png)

The problem that you are facing is quite difficult to debug, as there can be many reasons. In short, the exec function could not run setvars. The most likely reasons are: a problem with execution rights, PowerShell or something like that. Our experiment with manual launch will allow us to narrow down the range of possible defects.

**Comment by AdamMiltonBarker** [comment] 2021-07-14 01:27
I didn't remember posting here :) Yes that works and I can run that command with VS terminal also.

**Comment by sbobko** [comment] 2021-07-14 08:49
@AdamMiltonBarker okay, copy that. It is most likely that you have PowerShell version 5.1 (or so) , which is not detected by our extension. This is definitely our problem and it will be fixed soon, but you can install a newer version of PowerShell to make everything work right now:
**https://github.com/PowerShell/PowerShell/releases/tag/v7.1.3**

**Comment by AdamMiltonBarker** [comment] 2021-07-14 10:42
Hi the path is now found after the update (See bottom right of screen shot) but I still get an error.

![Capture](https://user-images.githubusercontent.com/6291410/125609108-d4ff1a47-36a4-4595-bbcb-329c0830da04.JPG)

**Comment by sbobko** [comment] 2021-07-15 09:20
@AdamMiltonBarker Okay, then there may be a problem with access rights. Try running VSCode as an Administrator.
I think this will solve the problem.

**Comment by AdamMiltonBarker** [comment] 2021-07-15 14:37
@sbobko thank you I will do later tonight and will let you know.

**Comment by AdamMiltonBarker** [comment] 2021-07-15 18:17
Nope sorry that isn't it either I have a new error now :( 
![nope](https://user-images.githubusercontent.com/6291410/125837579-587c8419-be44-439a-a76e-134096e75ce0.JPG)

**Comment by AdamMiltonBarker** [comment] 2021-07-15 18:19
OK hang on, after that I tried again and it worked. It looks the permissions is the issue.

**Comment by sbobko** [comment] 2021-07-21 13:56
Unfortunately, I do not know what the problem is with network drives, since it is not related to the extension. While there are no reports of insufficient permissions, however, I expect that we will add it in the near future or solve the problem differently. Thank you for your assistance in the search :).

**Comment by AdamMiltonBarker** [comment] 2021-07-21 23:46
No problem was just letting you know to resolve the issue it means I cannot use VS code in the usual way. Hope the issue helped.

**Comment by xmnboy** [comment] 2021-10-14 22:25
Adding reference to internal bug report > DEV1A-3312.

**Closed** 2022-03-16 13:20 UTC
